# Copy this file to .streamlit/secrets.toml and fill in your real values.

TELEGRAM_BOT_TOKEN = "8230608175:AAHnMtm1w3oLcsTridWX11NfQmBBFdtQMfw"
TELEGRAM_CHAT_ID = "8172522699"

EMAIL_SENDER = "abirami.kunasagaran@rohastecnic.com"
EMAIL_PASSWORD = "xltb jvix uieg jfts"
EMAIL_RECEIVER = "abiarchu8615@gmail.com
